name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    #- name: Publish
    #  run: dotnet pack --configuration Release && dotnet nuget push "bin/Anemonis.JsonRpc.ServiceClient/Release/Anemonis.JsonRpc.ServiceClient.1.17.0.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/StiftsEU/index.json"
    
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Publish GH Package
      uses: rohan-buchner/publish-gh-package@v1.1.4
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: "src/Anemonis.JsonRpc.ServiceClient/Anemonis.JsonRpc.ServiceClient.csproj"
        # NuGet package id, used for version detection & defaults to project name
        #PACKAGE_NAME: # optional
        # Filepath with version info, relative to root of repository & defaults to PROJECT_FILE_PATH
        VERSION_FILE_PATH: "src/Anemonis.JsonRpc.ServiceClient/Properties/ProjectInfo.props" # optional
        # Regex pattern to extract version info in a capturing group
        VERSION_REGEX: ^\s*<VersionPrefix>(.*)<\/VersionPrefix>\s*$ # optional, default is ^\s*<Version>(.*)<\/Version>\s*$
        # Useful with external providers like Nerdbank.GitVersioning, ignores VERSION_FILE_PATH & VERSION_REGEX
        #VERSION_STATIC: # optional
        # Flag to toggle git tagging, enabled by default
        #TAG_COMMIT: # optional, default is true
        # Format of the git tag, [*] gets replaced with actual version
        #TAG_FORMAT: # optional, default is v*
        # API key to authenticate with NuGet server
        NUGET_KEY: ${{ secrets.GITHUB_TOKEN }} # optional
        # NuGet server uri hosting the packages, defaults to https://nuget.pkg.github.com
        NUGET_SOURCE: nuget.pkg.github.com # optional, default is https://nuget.pkg.github.com
        # The Organisation Name
        ORGANISATION: StiftsEU # default is Organisation
        # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
        #INCLUDE_SYMBOLS: # optional