name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet nuget add source --username kinnajowa --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/StiftsEU/index.json" && dotnet pack --configuration Release && dotnet nuget push "/home/runner/work/json-rpc-client/json-rpc-client/bin/Anemonis.JsonRpc.ServiceClient/Release/Anemonis.JsonRpc.ServiceClient.1.17.0.nupkg" --api-key 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 --source "github"
